name: Deploy GH Pages
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Deploy GH Pages
    steps:
    - uses: actions/checkout@v2
    - id: Build-Vue
      uses: xRealNeon/VuePagesAction@1.0.1
      with:
        username: 'gaycookie'
        reponame: 'pogo-qr-gen'
        token: ${{ secrets.TOKEN }}